<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Assets/Scripts/ReturnModel.cs" Link="ReturnModel.cs" />
    <Compile Include="../../Assets/Scripts/ReturnChecks.cs" Link="ReturnChecks.cs" />
    <Compile Include="../../Assets/Scripts/ReturnPilot.cs" Link="ReturnPilot.cs" />
    <Compile Include="../../Assets/Scripts/CorePuzzle.cs" Link="CorePuzzle.cs" />
    <Compile Include="../../Assets/Scripts/ReworkModel.cs" Link="ReworkModel.cs" />
    <Compile Include="../../Assets/Scripts/ReworkPilot.cs" Link="ReworkPilot.cs" />
    <Compile Include="../../Assets/Scripts/ReworkChecks.cs" Link="ReworkChecks.cs" />
  </ItemGroup>
</Project>
